2025-02-11 15:40:05,419 (49570/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-11 15:40:05,419 (49570/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-11 15:40:05,425 (49570/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2025-02-11 15:41:01,605 (50447/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-11 15:41:01,607 (50447/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-11 15:41:01,621 (50447/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2025-02-11 15:43:04,448 (51700/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-11 15:43:04,449 (51700/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-02-11 15:43:05,091 (51700/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 758, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/main.py", line 729, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/local/Cellar/pgcli/4.1.0_1/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server at "3.126.212.11", port 5432 failed: fe_sendauth: no password supplied\n'
2025-02-11 15:43:16,897 (51856/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2025-02-11 15:43:16,897 (51856/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
